config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  concern :localizable do
    put :change_locale, controller: "application"
  end

  scope :admin, module: :admin, as: :admin do
    concerns :localizable
    draw :admin
  end

  scope "/", module: :web, as: :web do
    concerns :localizable
    draw :web
  end
end

app/views/web/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg px-4">
  <a href="<%= web_root_path %>" class="navbar-brand px-2">
    <%= image_tag "Logo.png", height: "40", width: "auto" %>
    <span class="brand-name">Leiva Investing Inc.</span>
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto">
      <a href="<%= web_root_path %>" class="text-decoration-none">
        <li class="nav-item px-md-3">
          <div class="nav-link"><%= t(".home") %></div>
        </li>
      </a>
      <% if current_user&.admin? %>
        <a href="<%= admin_root_path %>" class="text-decoration-none">
          <li class="nav-item px-md-3">
            <div class="nav-link"><%= t(".admin") %></div>
          </li>
        </a>
      <% end %>
<!--      <a href="<%#= web_change_locale_path %>" data-turbo-method="put" class="text-decoration-none">-->
<!--        <li class="nav-item px-md-3">-->
<!--          <div class="nav-link"><%#= t("change_language") %></div>-->
<!--        </li>-->
<!--      </a>-->
    </ul>
  </div>
</nav>

app/views/web/layouts/_scroll_widget.html.erb
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div class="tradingview-widget-container__widget"></div>
  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
      {
          "symbols": [
          {
              "proName": "FOREXCOM:SPXUSD",
              "title": "S&P 500 Index"
          },
          {
              "proName": "BITSTAMP:BTCUSD",
              "title": "Bitcoin"
          },
          {
              "description": "",
              "proName": "TSX:XEI"
          },
          {
              "description": "",
              "proName": "CAPITALCOM:GOLD"
          },
          {
              "description": "",
              "proName": "TSX:TSX"
          },
          {
              "description": "",
              "proName": "NYSE:MSCI"
          }
      ],
          "showSymbolLogo": true,
          "isTransparent": false,
          "displayMode": "adaptive",
          "colorTheme": "dark",
          "locale": "en"
      }
  </script>
</div>
<!-- TradingView Widget END -->

app/views/web/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leiva Investing Inc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "web", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "web", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "web/layouts/navbar" %>
    <%= render 'web/layouts/scroll_widget' %>
    <% if browser.device.mobile? %>
      <div class="container my-5 mx-auto text-center">
        <p><%= t(".desktop_available") %></p>
        <p><%= t(".go_laptop") %></p>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>